<?php

/**
 * PluginrdMenuItemsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrdMenuItemsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object PluginrdMenuItemsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('PluginrdMenuItems');
    }

    /**
     * Returns Query for elements that parent_id is null
     * 
     * @return Doctrine_Query
     */
    public function getParents() {
        return Doctrine_Query::create()
                ->from('RdMenuItems')
                ->where('parent_id is null ' )
                ->orderBy('ord ASC')
                ->execute();
    }

}