<?php

/**
 * PluginrdMenuModulesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrdMenuModulesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrdMenuModulesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrdMenuModules');
    }
}