<?php

/**
 * PluginrdMenuModules
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sinersis
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginrdMenuModules extends BaserdMenuModules {

    public function save(Doctrine_Connection $conn = null) {
//        $parent_id = $this->getRdMenuItems()->getParentId();
//
//        $q = Doctrine_Query::create()
//                        ->delete('rdMenuModules')
//                        ->where('name = ?', array($this->getName()));
//
//        if (!$this->isNew()) {
//            $q->andwhere('id != ?', array($this->getId()));
//        }
//
//        if ($parent_id) {
//
//            $q->andwhere('id != ?', array($parent_id));
//        }
//        $q->execute();


//        if ($parent_id) {
//
//            $modules = new rdMenuModules();
//            $modules->id = $parent_id;
//            $modules->name = $this->getName();
//            $modules->save();
//        }

        parent::save($conn);
    }

    public function delete(Doctrine_Connection $conn = null) {

        parent::delete($conn);
    }

}