<?php

/**
 * PluginrdMenuCredentialsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrdMenuCredentialsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrdMenuCredentialsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrdMenuCredentials');
    }
}