<?php

/**
 * PluginSystemTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSystemTaskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSystemTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSystemTask');
    }
}