generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 radmas_shadowbox
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_permission_rd_menu_permission
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ name, description ]
        batch_actions: []
      filter:
        display: [ name, description ]
      form:    ~
      edit:    ~
      new:     ~
