###################################################################
# This file is part of the daraint proyect.
# (c) 2010 RADMAS S.L. Rad(+) Technologies
#
# For the full copyright and license information, please view the
# LICENSE file that was distributed with this source code.
###################################################################

SystemLogger:
  tableName: system_logger
  actAs:                            [Timestampable, sfGuardUserLoggerBehavior]
  columns:
#    brand_id:                       { type: integer,  notnull: false, default: null }
#    territorial_id:                 { type: integer,  notnull: false, default: null }
    logger_id:                      { type: integer,  notnull: false, default: null }
    logger_class:                   { type: string(255), notnull: true, default: '' }
    sf_guard_user_id:               { type: integer,  notnull: false, default: null }
    name:                           { type: string(255), notnull: true, default: '' }
    level:                          { type: string(255), notnull: true, default: '' }    
    link:                           { type: string(255), notnull: true, default: '' }
    url:                            { type: string(255), notnull: true, default: '' }
    text:                           { type: string(5000), notnull: true, default: '' }
  relations:
#    Brands:                         { onDelete: CASCADE, local: brand_id, foreign: id }
#    Territorials:                   { onDelete: CASCADE, local: territorial_id , foreign: id }  


rdMenuItems:
  tableName: rd_menu_items
  actAs:                            [Timestampable]
  columns:
    parent_id:                      { type: integer, notnull: false, default: null }
    ord:                            { type: integer, notnull: false, default: '' }
    name:                           { type: string(255), notnull: true, default: null }
    target:                         { type: string(255), notnull: true, default: '' }
    css:                            { type: string(255), notnull: true, default: '' }
    url:                            { type: string(255), notnull: true, default: '' }
    color:                          { type: string(255), notnull: true, default: '' }
  relations:
    rdMenuItems:                    { local: parent_id , foreign: id }

rdMenuModules:
  tableName: rd_menu_modules
  actAs:                            [Timestampable]
  columns:
    rd_main_menu_item_id:           { type: integer,  notnull: true, default: null }
    name:                           { type: string(255), notnull: true, default: null }
  relations:
    rdMenuItems:                    { local: rd_main_menu_item_id , foreign: id }
  indexes:
    rd_main_menu_item_id_name_index:
      fields: [rd_main_menu_item_id, name]
      type: unique

rdMenuCredentials:
  tableName: rd_menu_credentials
  actAs:                            [Timestampable]
  columns:
    rd_main_menu_item_id:           { type: integer,  notnull: true, default: null }
    sf_guard_permission_id:         { type: integer,  notnull: true, default: null }
  relations:
    sfGuardPermission:              { local: sf_guard_permission_id , foreign: id }    
    rdMenuItems:                    { local: rd_main_menu_item_id , foreign: id }

SystemTask:
  tableName: system_task
  actAs:                            [Timestampable]
  columns:
    name:                           { type: string(255), notnull: true, default: '' }
    is_active:                      { type: boolean, default: 1 }